language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAXKZ6AV6CARVTB6CN
  skip_cleanup: true
  local_dir: build
  default_text_charset: utf-8
  bucket: michael-static-react-scribbler
  region: us-east-1
  secret_access_key:
    secure: VjdDb+N+AmBVTpdV742eBgKjooSW/zLHdcjav8OsNhz7+V0LXFNEQRWklHpmffbyE8D54tHL2lv24JzKbqo15wa/fvbKp95SrkEavzb2kQ5relrC+laO+EFxxUopFxEwlRHIzhG1CieE7oElMrsIlEYP6BxxiFIUkNAlYWYy7jdH3mKxZI9v5K+qjlTBysCALwO2HLqhgftNyMcCHO7Y3+JDsWuWT3DzT/IG2/klGgC69RgeFFTTHVz5oWcZRd59e2bxK7P5ezrbqhf+dcDVv3F3Bjobm9rzy7NOo0eceneqBkOne/oQyTPJDUV3xJlxhjYLAGjyuB7RHCVGycbyUH3hIEQ1XhGMc0lygl+pjjkSHKhzABiuMt5dxJjjXLYGZ69VakI1zEE29eNcCcUND3MNi9Rge5m8N2p3n6sL8jRsYq6ImHe0s4HRi6dIC4T1lif63hL5YNINtdVRrsHqevVrAzca9RMH6CcQhGZOl0fSvn5eUjjCeoggIP2+/UsNSMGsBveDA7VlEhEL5U9GSt0iJ43rs3aNgGWqtDWhnRtwqdD8+VZ/lf+iwhJB8Eodi/s1h9ojZvmuhbCBpKtONy7cRhJCEcYs/2rRO3ZsB7p+s0zA9ZoIviGmPUiNzcLivf739i5bL2qE41GWwshkVi3Pqs3sp+J9jXV+2tIht7I=
