language: node_js
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: "AKIAJPINEAC63Q5SPFQQ"
  secret_access_key: "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"
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "michael-static-react-scribbler"
  region: us-east-1