language: node_js
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: "AKIAXKZ6AV6CBBOSCFXD"
  secret_access_key: "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"
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "michael-static-react-scribbler"
  region: us-east-1